# https://docs.nav2.org/configuration/packages/configuring-behavior-server.html
# Default behavior: /opt/ros/jazzy/share/nav2_bt_navigator/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
behavior_server:
  ros__parameters:
    use_sim_time: true
    costmap_topic: local_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    transform_tolerance: 5.0
    local_frame: odom
    global_frame: map
    robot_base_frame: base_link
    behavior_plugins:
          ["spin", "backup", "drive_on_heading", "wait"]
    drive_on_heading:
      plugin: "nav2_behaviors::DriveOnHeading"
    spin:
      plugin: "nav2_behaviors::Spin"
    backup:
      plugin: "nav2_behaviors::BackUp"
    wait:
      plugin: "nav2_behaviors::Wait"
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0471975511965976
    min_rotational_vel: 0.08726646259971647
    rotational_acc_lim: 5.235987755982989
    enable_stamped_cmd_vel: false
