# https://docs.nav2.org/configuration/packages/configuring-bt-navigator.html
# 
bt_navigator:
  ros__parameters:
    navigators: {‘navigate_to_pose’, ‘navigate_through_poses’}
    bt_loop_duration: 10
    default_server_timeout: 20
    transform_tolerance: 1.0
    global_frame: map
    robot_base_frame: base_link
    odom_topic: odom
    use_sim_time: false
    error_code_names:
      - compute_path_error_code
      - follow_path_error_code
    navigate_to_pose:
      plugin: "nav2_bt_navigator::NavigateToPoseNavigator"
    navigate_through_poses:
      plugin: "nav2_bt_navigator::NavigateThroughPosesNavigator"